### PR TITLE
FISH-7360 Asadmin Recorder Button Missing

### PR DESCRIPTION
**Pull request by Pandrex247**
Remove mention of the button until we've fixed it.

### CODE REVIEW

**Review by fturizo — APPROVED** [review]
LGTM

**Comment by fturizo** [comment]
@Pandrex247, just to confirm, the button in question is not rendered into any version of Payara Server 6, either Enterprise and Community editions, correct?

**Comment by Pandrex247** [comment]
> Pandrex247, just to confirm, the button in question is not rendered into any version of Payara Server 6, either Enterprise or Community editions, correct?

Correct

**Comment by JamesHillyard** [comment]
> Actually, not correct! It's present in Community

In this case the documentation just needs updating for Enterprise

**Review by JamesHillyard — APPROVED** [review]

**Pull request merged**
