### PR TITLE
FISH-6495 : hazelcastConfigurationFile property documentation

### PR DESCRIPTION
**Pull request by luiseufrasio**

### CODE REVIEW

**Review by Pandrex247 — APPROVED** [review]

**Comment by JamesHillyard** [comment]
Is this only supported in embedded? If so looks good, if not then it'll need documenting for the other arquillian connectors

**Comment by JamesHillyard** [comment]
Also, please don't merge this until the documentation cuts have been taken for the current releases

**Comment by luiseufrasio** [comment]
> Is this only supported in embedded? If so looks good, if not then it'll need documenting for the other arquillian connectors

Yes, only for embedded.

**Review by JamesHillyard — APPROVED** [review]

**Comment by JamesHillyard** [comment]
Payara 6 PR: https://github.com/payara/Payara-Documentation/pull/148

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
