### PR TITLE
FISH-7734 Ecosystem docs update

### PR DESCRIPTION
**Pull request by jGauravGupta**

### CODE REVIEW

**Review by fturizo — APPROVED** [review]
Looks good, I did some small grammar and layout fixes.

**Comment by fturizo** [comment]
@jGauravGupta, PR is reviewed. Question, do these changes only apply to Platform 6, or is 5 affected too?

**Comment by fturizo** [comment]
@jGauravGupta, I have made a matching PR to the `master` branch with all of the relevant changes included here.

**Comment by jGauravGupta** [comment]
Thanks @fturizo

**Pull request merged**
