### PR TITLE
Fish 6474 add doc for vscode tranformation integration

### PR DESCRIPTION
**Pull request by breakponchito**
Adding documentation for transformer integration with VSCode

### CODE REVIEW

**Review by fturizo — CHANGES_REQUESTED** [review]
@breakponchito, I have done some rewriting of the documentation on my end due to some inconsistencies in the documentation:

* Every instance of the word "migrate" has been renamed to "transform", since the 2 words have different connotations and the second one is in line with the official set of features offered by the Eclipse Transformer.
* I have simplified the structure of each section since the feature should be simple to use and not be overly explained.

However, there are some details still pending:

* On the images where the IDE asks the user to confirm the overriding actions, the texts should read:
** "Are you sure that you want to override this file?"
** "Are you sure that you want to override all files in this folder?"
* The images for the destination folder selections show that the file dialog contents are in Spanish,  please switch to proper images in English.

**Comment by breakponchito** [comment]
> 

I already attended the comments

**Review by fturizo — APPROVED** [review]
Changes made in the submitted screenshots are OK, can proceed to merge.

**Comment by fturizo** [comment]
Please, port this PR to the `payara6-master` branch after merging.

**Pull request merged**
