### PR TITLE
FISH-7837: adding doc for microprofile 6.1

### PR DESCRIPTION
**Pull request by breakponchito**
Adding documentation to include microprofile 6.1

### CODE REVIEW

**Review by Pandrex247 — APPROVED** [review]

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
The individual pages need updating too.

* The config page still lists 3.0.2
* Telemetry page still lists 1.0

**Comment by breakponchito** [comment]
> The individual pages need updating too.
> 
> * The config page still lists 3.0.2
> * Telemetry page still lists 1.0

now all of them were updated with last versions from MP 6.1, please check

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Changes shouldn't be made to the spec pages under `community`
This affects both.

You either need to make the changes to both, or delete all of the override pages (e.g. Fault Tolerance.adoc) under `community` and `enterprise` and move them to the generic `docs` folder

**Review by fturizo — APPROVED** [review]
LGTM

**Pull request merged**
